/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as DiagnosticoEscolaRouteImport } from './routes/diagnostico-escola'
import { Route as DiagnosticoIlpiRouteImport } from './routes/diagnostico-ilpi'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EscolasRouteImport } from './routes/escolas'
import { Route as IlpiRouteImport } from './routes/ilpi'
import { Route as IntercorrenciaRouteImport } from './routes/intercorrencia'
import { Route as LaresDeIdososRouteImport } from './routes/lares-de-idosos'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OdontologiaRouteImport } from './routes/odontologia'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SucessoRouteImport } from './routes/sucesso'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGestorRouteImport } from './routes/_authenticated/gestor'
import { Route as AuthenticatedHojeRouteImport } from './routes/_authenticated/hoje'
import { Route as AuthenticatedLogisticaRouteImport } from './routes/_authenticated/logistica'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedSaudeRouteImport } from './routes/_authenticated/saude'
import { Route as AcaoTipoRouteImport } from './routes/acao.$tipo'
import { Route as AuthRegisterRouteImport } from './routes/auth_.register'
import { Route as HistoricoLocalIdRouteImport } from './routes/historico.$localId'
import { Route as IlpiIndexRouteImport } from './routes/ilpi.index'
import { Route as IlpiAuditoriaRouteImport } from './routes/ilpi.auditoria'
import { Route as IlpiChecklistsRouteImport } from './routes/ilpi.checklists'
import { Route as IlpiSinaisRouteImport } from './routes/ilpi.sinais'
import { Route as PublicoSlugRouteImport } from './routes/publico.$slug'
import { Route as SeloAreaIdRouteImport } from './routes/selo.$areaId'
import { Route as ValidarHashRouteImport } from './routes/validar.$hash'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedChecklistIndexRouteImport } from './routes/_authenticated/checklist.index'
import { Route as AuthenticatedChecklistIdRouteImport } from './routes/_authenticated/checklist.$id'
import { Route as AuthenticatedEtiquetasUnitIdRouteImport } from './routes/_authenticated/etiquetas.$unitId'
import { Route as AuthenticatedOnboardingHealthRouteImport } from './routes/_authenticated/onboarding.health'
import { Route as AuthenticatedOnboardingSetupRouteImport } from './routes/_authenticated/onboarding.setup'
import { Route as AuthenticatedOnboardingStep1RouteImport } from './routes/_authenticated/onboarding.step-1'
import { Route as AuthenticatedOnboardingStep2RouteImport } from './routes/_authenticated/onboarding.step-2'
import { Route as AuthenticatedOnboardingStep3RouteImport } from './routes/_authenticated/onboarding.step-3'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as AuthenticatedPainelAcademiasRouteImport } from './routes/_authenticated/painel.academias'
import { Route as AuthenticatedPainelAcessosRouteImport } from './routes/_authenticated/painel.acessos'
import { Route as AuthenticatedPainelAssinantesRouteImport } from './routes/_authenticated/painel.assinantes'
import { Route as AuthenticatedPainelAssinaturaRouteImport } from './routes/_authenticated/painel.assinatura'
import { Route as AuthenticatedPainelCapaRouteImport } from './routes/_authenticated/painel.capa'
import { Route as AuthenticatedPainelChecklistsRouteImport } from './routes/_authenticated/painel.checklists'
import { Route as AuthenticatedPainelConformidadeRouteImport } from './routes/_authenticated/painel.conformidade'
import { Route as AuthenticatedPainelDocumentosRouteImport } from './routes/_authenticated/painel.documentos'
import { Route as AuthenticatedPainelEsterilizacaoRouteImport } from './routes/_authenticated/painel.esterilizacao'
import { Route as AuthenticatedPainelEstoqueRouteImport } from './routes/_authenticated/painel.estoque'
import { Route as AuthenticatedPainelInsumosRouteImport } from './routes/_authenticated/painel.insumos'
import { Route as AuthenticatedPainelLogisticaRouteImport } from './routes/_authenticated/painel.logistica'
import { Route as AuthenticatedPainelPastasRouteImport } from './routes/_authenticated/painel.pastas'
import { Route as AuthenticatedPainelPmocRouteImport } from './routes/_authenticated/painel.pmoc'
import { Route as AuthenticatedPainelPrecificacaoRouteImport } from './routes/_authenticated/painel.precificacao'
import { Route as AuthenticatedPainelRdcRouteImport } from './routes/_authenticated/painel.rdc'
import { Route as AuthenticatedPainelSuitesRouteImport } from './routes/_authenticated/painel.suites'
import { Route as AuthenticatedPainelTreinamentosRouteImport } from './routes/_authenticated/painel.treinamentos'
import { Route as AuthenticatedSuperadminClientesRouteImport } from './routes/_authenticated/superadmin.clientes'
import { Route as AuthenticatedSuperadminCompliceRouteImport } from './routes/_authenticated/superadmin.complice'
import { Route as AuthenticatedSuperadminMetricasRouteImport } from './routes/_authenticated/superadmin.metricas'
import { Route as AuthenticatedSuperadminPagamentosRouteImport } from './routes/_authenticated/superadmin.pagamentos'
import { Route as AuthenticatedSuperadminRegulatorioRouteImport } from './routes/_authenticated/superadmin.regulatorio'
import { Route as AppOperadorIndexRouteImport } from './routes/app.operador.index'
import { Route as QUnitIdTokenRouteImport } from './routes/q.$unitId.$token'
import { Route as AuthenticatedPainelPrefeiturasIndexRouteImport } from './routes/_authenticated/painel.prefeituras.index'
import { Route as AuthenticatedPainelPrefeiturasDashboardRouteImport } from './routes/_authenticated/painel.prefeituras.dashboard'
import { Route as AuthenticatedPainelRdcIndexRouteImport } from './routes/_authenticated/painel.rdc.index'
import { Route as AuthenticatedPainelRdcDiagnosticoRouteImport } from './routes/_authenticated/painel.rdc.diagnostico'
import { Route as AuthenticatedPainelRdcEvidenciasRouteImport } from './routes/_authenticated/painel.rdc.evidencias'
import { Route as AuthenticatedPainelRdcPlanoRouteImport } from './routes/_authenticated/painel.rdc.plano'
import { Route as AuthenticatedPainelRdcRiscosRouteImport } from './routes/_authenticated/painel.rdc.riscos'
import { Route as AuthenticatedPainelUnidadesIndexRouteImport } from './routes/_authenticated/painel.unidades.index'
import { Route as AuthenticatedPainelUnidadesIdRouteImport } from './routes/_authenticated/painel.unidades.$id'
import { Route as ApiPublicHooksComplianceSchedulerRouteImport } from './routes/api/public/hooks/compliance-scheduler'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'
import { Route as AppOperadorUnitIdTokenRouteImport } from './routes/app.operador.$unitId.$token'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoEscolaRoute = DiagnosticoEscolaRouteImport.update({
  id: '/diagnostico-escola',
  path: '/diagnostico-escola',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoIlpiRoute = DiagnosticoIlpiRouteImport.update({
  id: '/diagnostico-ilpi',
  path: '/diagnostico-ilpi',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolasRoute = EscolasRouteImport.update({
  id: '/escolas',
  path: '/escolas',
  getParentRoute: () => rootRouteImport,
} as any)
const IlpiRoute = IlpiRouteImport.update({
  id: '/ilpi',
  path: '/ilpi',
  getParentRoute: () => rootRouteImport,
} as any)
const IntercorrenciaRoute = IntercorrenciaRouteImport.update({
  id: '/intercorrencia',
  path: '/intercorrencia',
  getParentRoute: () => rootRouteImport,
} as any)
const LaresDeIdososRoute = LaresDeIdososRouteImport.update({
  id: '/lares-de-idosos',
  path: '/lares-de-idosos',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OdontologiaRoute = OdontologiaRouteImport.update({
  id: '/odontologia',
  path: '/odontologia',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SucessoRoute = SucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestorRoute = AuthenticatedGestorRouteImport.update({
  id: '/gestor',
  path: '/gestor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHojeRoute = AuthenticatedHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogisticaRoute = AuthenticatedLogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaudeRoute = AuthenticatedSaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AcaoTipoRoute = AcaoTipoRouteImport.update({
  id: '/acao/$tipo',
  path: '/acao/$tipo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth_/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoLocalIdRoute = HistoricoLocalIdRouteImport.update({
  id: '/historico/$localId',
  path: '/historico/$localId',
  getParentRoute: () => rootRouteImport,
} as any)
const IlpiIndexRoute = IlpiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IlpiRoute,
} as any)
const IlpiAuditoriaRoute = IlpiAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => IlpiRoute,
} as any)
const IlpiChecklistsRoute = IlpiChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => IlpiRoute,
} as any)
const IlpiSinaisRoute = IlpiSinaisRouteImport.update({
  id: '/sinais',
  path: '/sinais',
  getParentRoute: () => IlpiRoute,
} as any)
const PublicoSlugRoute = PublicoSlugRouteImport.update({
  id: '/publico/$slug',
  path: '/publico/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SeloAreaIdRoute = SeloAreaIdRouteImport.update({
  id: '/selo/$areaId',
  path: '/selo/$areaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidarHashRoute = ValidarHashRouteImport.update({
  id: '/validar/$hash',
  path: '/validar/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedChecklistIndexRoute =
  AuthenticatedChecklistIndexRouteImport.update({
    id: '/checklist/',
    path: '/checklist/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecklistIdRoute =
  AuthenticatedChecklistIdRouteImport.update({
    id: '/checklist/$id',
    path: '/checklist/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEtiquetasUnitIdRoute =
  AuthenticatedEtiquetasUnitIdRouteImport.update({
    id: '/etiquetas/$unitId',
    path: '/etiquetas/$unitId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingHealthRoute =
  AuthenticatedOnboardingHealthRouteImport.update({
    id: '/onboarding/health',
    path: '/onboarding/health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingSetupRoute =
  AuthenticatedOnboardingSetupRouteImport.update({
    id: '/onboarding/setup',
    path: '/onboarding/setup',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingStep1Route =
  AuthenticatedOnboardingStep1RouteImport.update({
    id: '/onboarding/step-1',
    path: '/onboarding/step-1',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingStep2Route =
  AuthenticatedOnboardingStep2RouteImport.update({
    id: '/onboarding/step-2',
    path: '/onboarding/step-2',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingStep3Route =
  AuthenticatedOnboardingStep3RouteImport.update({
    id: '/onboarding/step-3',
    path: '/onboarding/step-3',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAcademiasRoute =
  AuthenticatedPainelAcademiasRouteImport.update({
    id: '/academias',
    path: '/academias',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAcessosRoute =
  AuthenticatedPainelAcessosRouteImport.update({
    id: '/acessos',
    path: '/acessos',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAssinantesRoute =
  AuthenticatedPainelAssinantesRouteImport.update({
    id: '/assinantes',
    path: '/assinantes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAssinaturaRoute =
  AuthenticatedPainelAssinaturaRouteImport.update({
    id: '/assinatura',
    path: '/assinatura',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelCapaRoute = AuthenticatedPainelCapaRouteImport.update({
  id: '/capa',
  path: '/capa',
  getParentRoute: () => AuthenticatedPainelRoute,
} as any)
const AuthenticatedPainelChecklistsRoute =
  AuthenticatedPainelChecklistsRouteImport.update({
    id: '/checklists',
    path: '/checklists',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelConformidadeRoute =
  AuthenticatedPainelConformidadeRouteImport.update({
    id: '/conformidade',
    path: '/conformidade',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelDocumentosRoute =
  AuthenticatedPainelDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelEsterilizacaoRoute =
  AuthenticatedPainelEsterilizacaoRouteImport.update({
    id: '/esterilizacao',
    path: '/esterilizacao',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelEstoqueRoute =
  AuthenticatedPainelEstoqueRouteImport.update({
    id: '/estoque',
    path: '/estoque',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelInsumosRoute =
  AuthenticatedPainelInsumosRouteImport.update({
    id: '/insumos',
    path: '/insumos',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelLogisticaRoute =
  AuthenticatedPainelLogisticaRouteImport.update({
    id: '/logistica',
    path: '/logistica',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelPastasRoute =
  AuthenticatedPainelPastasRouteImport.update({
    id: '/pastas',
    path: '/pastas',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelPmocRoute = AuthenticatedPainelPmocRouteImport.update({
  id: '/pmoc',
  path: '/pmoc',
  getParentRoute: () => AuthenticatedPainelRoute,
} as any)
const AuthenticatedPainelPrecificacaoRoute =
  AuthenticatedPainelPrecificacaoRouteImport.update({
    id: '/precificacao',
    path: '/precificacao',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelRdcRoute = AuthenticatedPainelRdcRouteImport.update({
  id: '/rdc',
  path: '/rdc',
  getParentRoute: () => AuthenticatedPainelRoute,
} as any)
const AuthenticatedPainelSuitesRoute =
  AuthenticatedPainelSuitesRouteImport.update({
    id: '/suites',
    path: '/suites',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelTreinamentosRoute =
  AuthenticatedPainelTreinamentosRouteImport.update({
    id: '/treinamentos',
    path: '/treinamentos',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedSuperadminClientesRoute =
  AuthenticatedSuperadminClientesRouteImport.update({
    id: '/superadmin/clientes',
    path: '/superadmin/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperadminCompliceRoute =
  AuthenticatedSuperadminCompliceRouteImport.update({
    id: '/superadmin/complice',
    path: '/superadmin/complice',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperadminMetricasRoute =
  AuthenticatedSuperadminMetricasRouteImport.update({
    id: '/superadmin/metricas',
    path: '/superadmin/metricas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperadminPagamentosRoute =
  AuthenticatedSuperadminPagamentosRouteImport.update({
    id: '/superadmin/pagamentos',
    path: '/superadmin/pagamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperadminRegulatorioRoute =
  AuthenticatedSuperadminRegulatorioRouteImport.update({
    id: '/superadmin/regulatorio',
    path: '/superadmin/regulatorio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AppOperadorIndexRoute = AppOperadorIndexRouteImport.update({
  id: '/app/operador/',
  path: '/app/operador/',
  getParentRoute: () => rootRouteImport,
} as any)
const QUnitIdTokenRoute = QUnitIdTokenRouteImport.update({
  id: '/q/$unitId/$token',
  path: '/q/$unitId/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelPrefeiturasIndexRoute =
  AuthenticatedPainelPrefeiturasIndexRouteImport.update({
    id: '/prefeituras/',
    path: '/prefeituras/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelPrefeiturasDashboardRoute =
  AuthenticatedPainelPrefeiturasDashboardRouteImport.update({
    id: '/prefeituras/dashboard',
    path: '/prefeituras/dashboard',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelRdcIndexRoute =
  AuthenticatedPainelRdcIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelRdcRoute,
  } as any)
const AuthenticatedPainelRdcDiagnosticoRoute =
  AuthenticatedPainelRdcDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedPainelRdcRoute,
  } as any)
const AuthenticatedPainelRdcEvidenciasRoute =
  AuthenticatedPainelRdcEvidenciasRouteImport.update({
    id: '/evidencias',
    path: '/evidencias',
    getParentRoute: () => AuthenticatedPainelRdcRoute,
  } as any)
const AuthenticatedPainelRdcPlanoRoute =
  AuthenticatedPainelRdcPlanoRouteImport.update({
    id: '/plano',
    path: '/plano',
    getParentRoute: () => AuthenticatedPainelRdcRoute,
  } as any)
const AuthenticatedPainelRdcRiscosRoute =
  AuthenticatedPainelRdcRiscosRouteImport.update({
    id: '/riscos',
    path: '/riscos',
    getParentRoute: () => AuthenticatedPainelRdcRoute,
  } as any)
const AuthenticatedPainelUnidadesIndexRoute =
  AuthenticatedPainelUnidadesIndexRouteImport.update({
    id: '/unidades/',
    path: '/unidades/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelUnidadesIdRoute =
  AuthenticatedPainelUnidadesIdRouteImport.update({
    id: '/unidades/$id',
    path: '/unidades/$id',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const ApiPublicHooksComplianceSchedulerRoute =
  ApiPublicHooksComplianceSchedulerRouteImport.update({
    id: '/api/public/hooks/compliance-scheduler',
    path: '/api/public/hooks/compliance-scheduler',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOperadorUnitIdTokenRoute = AppOperadorUnitIdTokenRouteImport.update({
  id: '/app/operador/$unitId/$token',
  path: '/app/operador/$unitId/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diagnostico-escola': typeof DiagnosticoEscolaRoute
  '/diagnostico-ilpi': typeof DiagnosticoIlpiRoute
  '/entrar': typeof EntrarRoute
  '/escolas': typeof EscolasRoute
  '/ilpi': typeof IlpiRouteWithChildren
  '/intercorrencia': typeof IntercorrenciaRoute
  '/lares-de-idosos': typeof LaresDeIdososRoute
  '/mcp': typeof McpRoute
  '/menu': typeof MenuRoute
  '/odontologia': typeof OdontologiaRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sucesso': typeof SucessoRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gestor': typeof AuthenticatedGestorRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/logistica': typeof AuthenticatedLogisticaRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/saude': typeof AuthenticatedSaudeRoute
  '/acao/$tipo': typeof AcaoTipoRoute
  '/auth/register': typeof AuthRegisterRoute
  '/historico/$localId': typeof HistoricoLocalIdRoute
  '/ilpi/auditoria': typeof IlpiAuditoriaRoute
  '/ilpi/checklists': typeof IlpiChecklistsRoute
  '/ilpi/sinais': typeof IlpiSinaisRoute
  '/publico/$slug': typeof PublicoSlugRoute
  '/selo/$areaId': typeof SeloAreaIdRoute
  '/validar/$hash': typeof ValidarHashRoute
  '/ilpi/': typeof IlpiIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/checklist/$id': typeof AuthenticatedChecklistIdRoute
  '/etiquetas/$unitId': typeof AuthenticatedEtiquetasUnitIdRoute
  '/onboarding/health': typeof AuthenticatedOnboardingHealthRoute
  '/onboarding/setup': typeof AuthenticatedOnboardingSetupRoute
  '/onboarding/step-1': typeof AuthenticatedOnboardingStep1Route
  '/onboarding/step-2': typeof AuthenticatedOnboardingStep2Route
  '/onboarding/step-3': typeof AuthenticatedOnboardingStep3Route
  '/painel/academias': typeof AuthenticatedPainelAcademiasRoute
  '/painel/acessos': typeof AuthenticatedPainelAcessosRoute
  '/painel/assinantes': typeof AuthenticatedPainelAssinantesRoute
  '/painel/assinatura': typeof AuthenticatedPainelAssinaturaRoute
  '/painel/capa': typeof AuthenticatedPainelCapaRoute
  '/painel/checklists': typeof AuthenticatedPainelChecklistsRoute
  '/painel/conformidade': typeof AuthenticatedPainelConformidadeRoute
  '/painel/documentos': typeof AuthenticatedPainelDocumentosRoute
  '/painel/esterilizacao': typeof AuthenticatedPainelEsterilizacaoRoute
  '/painel/estoque': typeof AuthenticatedPainelEstoqueRoute
  '/painel/insumos': typeof AuthenticatedPainelInsumosRoute
  '/painel/logistica': typeof AuthenticatedPainelLogisticaRoute
  '/painel/pastas': typeof AuthenticatedPainelPastasRoute
  '/painel/pmoc': typeof AuthenticatedPainelPmocRoute
  '/painel/precificacao': typeof AuthenticatedPainelPrecificacaoRoute
  '/painel/rdc': typeof AuthenticatedPainelRdcRouteWithChildren
  '/painel/suites': typeof AuthenticatedPainelSuitesRoute
  '/painel/treinamentos': typeof AuthenticatedPainelTreinamentosRoute
  '/superadmin/clientes': typeof AuthenticatedSuperadminClientesRoute
  '/superadmin/complice': typeof AuthenticatedSuperadminCompliceRoute
  '/superadmin/metricas': typeof AuthenticatedSuperadminMetricasRoute
  '/superadmin/pagamentos': typeof AuthenticatedSuperadminPagamentosRoute
  '/superadmin/regulatorio': typeof AuthenticatedSuperadminRegulatorioRoute
  '/q/$unitId/$token': typeof QUnitIdTokenRoute
  '/checklist/': typeof AuthenticatedChecklistIndexRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
  '/app/operador/': typeof AppOperadorIndexRoute
  '/painel/prefeituras/dashboard': typeof AuthenticatedPainelPrefeiturasDashboardRoute
  '/painel/rdc/diagnostico': typeof AuthenticatedPainelRdcDiagnosticoRoute
  '/painel/rdc/evidencias': typeof AuthenticatedPainelRdcEvidenciasRoute
  '/painel/rdc/plano': typeof AuthenticatedPainelRdcPlanoRoute
  '/painel/rdc/riscos': typeof AuthenticatedPainelRdcRiscosRoute
  '/painel/unidades/$id': typeof AuthenticatedPainelUnidadesIdRoute
  '/api/public/hooks/compliance-scheduler': typeof ApiPublicHooksComplianceSchedulerRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/app/operador/$unitId/$token': typeof AppOperadorUnitIdTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/painel/prefeituras/': typeof AuthenticatedPainelPrefeiturasIndexRoute
  '/painel/rdc/': typeof AuthenticatedPainelRdcIndexRoute
  '/painel/unidades/': typeof AuthenticatedPainelUnidadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diagnostico-escola': typeof DiagnosticoEscolaRoute
  '/diagnostico-ilpi': typeof DiagnosticoIlpiRoute
  '/entrar': typeof EntrarRoute
  '/escolas': typeof EscolasRoute
  '/intercorrencia': typeof IntercorrenciaRoute
  '/lares-de-idosos': typeof LaresDeIdososRoute
  '/mcp': typeof McpRoute
  '/menu': typeof MenuRoute
  '/odontologia': typeof OdontologiaRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sucesso': typeof SucessoRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gestor': typeof AuthenticatedGestorRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/logistica': typeof AuthenticatedLogisticaRoute
  '/saude': typeof AuthenticatedSaudeRoute
  '/acao/$tipo': typeof AcaoTipoRoute
  '/auth/register': typeof AuthRegisterRoute
  '/historico/$localId': typeof HistoricoLocalIdRoute
  '/ilpi/auditoria': typeof IlpiAuditoriaRoute
  '/ilpi/checklists': typeof IlpiChecklistsRoute
  '/ilpi/sinais': typeof IlpiSinaisRoute
  '/publico/$slug': typeof PublicoSlugRoute
  '/selo/$areaId': typeof SeloAreaIdRoute
  '/validar/$hash': typeof ValidarHashRoute
  '/ilpi': typeof IlpiIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/checklist/$id': typeof AuthenticatedChecklistIdRoute
  '/etiquetas/$unitId': typeof AuthenticatedEtiquetasUnitIdRoute
  '/onboarding/health': typeof AuthenticatedOnboardingHealthRoute
  '/onboarding/setup': typeof AuthenticatedOnboardingSetupRoute
  '/onboarding/step-1': typeof AuthenticatedOnboardingStep1Route
  '/onboarding/step-2': typeof AuthenticatedOnboardingStep2Route
  '/onboarding/step-3': typeof AuthenticatedOnboardingStep3Route
  '/painel/academias': typeof AuthenticatedPainelAcademiasRoute
  '/painel/acessos': typeof AuthenticatedPainelAcessosRoute
  '/painel/assinantes': typeof AuthenticatedPainelAssinantesRoute
  '/painel/assinatura': typeof AuthenticatedPainelAssinaturaRoute
  '/painel/capa': typeof AuthenticatedPainelCapaRoute
  '/painel/checklists': typeof AuthenticatedPainelChecklistsRoute
  '/painel/conformidade': typeof AuthenticatedPainelConformidadeRoute
  '/painel/documentos': typeof AuthenticatedPainelDocumentosRoute
  '/painel/esterilizacao': typeof AuthenticatedPainelEsterilizacaoRoute
  '/painel/estoque': typeof AuthenticatedPainelEstoqueRoute
  '/painel/insumos': typeof AuthenticatedPainelInsumosRoute
  '/painel/logistica': typeof AuthenticatedPainelLogisticaRoute
  '/painel/pastas': typeof AuthenticatedPainelPastasRoute
  '/painel/pmoc': typeof AuthenticatedPainelPmocRoute
  '/painel/precificacao': typeof AuthenticatedPainelPrecificacaoRoute
  '/painel/suites': typeof AuthenticatedPainelSuitesRoute
  '/painel/treinamentos': typeof AuthenticatedPainelTreinamentosRoute
  '/superadmin/clientes': typeof AuthenticatedSuperadminClientesRoute
  '/superadmin/complice': typeof AuthenticatedSuperadminCompliceRoute
  '/superadmin/metricas': typeof AuthenticatedSuperadminMetricasRoute
  '/superadmin/pagamentos': typeof AuthenticatedSuperadminPagamentosRoute
  '/superadmin/regulatorio': typeof AuthenticatedSuperadminRegulatorioRoute
  '/q/$unitId/$token': typeof QUnitIdTokenRoute
  '/checklist': typeof AuthenticatedChecklistIndexRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
  '/app/operador': typeof AppOperadorIndexRoute
  '/painel/prefeituras/dashboard': typeof AuthenticatedPainelPrefeiturasDashboardRoute
  '/painel/rdc/diagnostico': typeof AuthenticatedPainelRdcDiagnosticoRoute
  '/painel/rdc/evidencias': typeof AuthenticatedPainelRdcEvidenciasRoute
  '/painel/rdc/plano': typeof AuthenticatedPainelRdcPlanoRoute
  '/painel/rdc/riscos': typeof AuthenticatedPainelRdcRiscosRoute
  '/painel/unidades/$id': typeof AuthenticatedPainelUnidadesIdRoute
  '/api/public/hooks/compliance-scheduler': typeof ApiPublicHooksComplianceSchedulerRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/app/operador/$unitId/$token': typeof AppOperadorUnitIdTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/painel/prefeituras': typeof AuthenticatedPainelPrefeiturasIndexRoute
  '/painel/rdc': typeof AuthenticatedPainelRdcIndexRoute
  '/painel/unidades': typeof AuthenticatedPainelUnidadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diagnostico-escola': typeof DiagnosticoEscolaRoute
  '/diagnostico-ilpi': typeof DiagnosticoIlpiRoute
  '/entrar': typeof EntrarRoute
  '/escolas': typeof EscolasRoute
  '/ilpi': typeof IlpiRouteWithChildren
  '/intercorrencia': typeof IntercorrenciaRoute
  '/lares-de-idosos': typeof LaresDeIdososRoute
  '/mcp': typeof McpRoute
  '/menu': typeof MenuRoute
  '/odontologia': typeof OdontologiaRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sucesso': typeof SucessoRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gestor': typeof AuthenticatedGestorRoute
  '/_authenticated/hoje': typeof AuthenticatedHojeRoute
  '/_authenticated/logistica': typeof AuthenticatedLogisticaRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteWithChildren
  '/_authenticated/saude': typeof AuthenticatedSaudeRoute
  '/acao/$tipo': typeof AcaoTipoRoute
  '/auth_/register': typeof AuthRegisterRoute
  '/historico/$localId': typeof HistoricoLocalIdRoute
  '/ilpi/auditoria': typeof IlpiAuditoriaRoute
  '/ilpi/checklists': typeof IlpiChecklistsRoute
  '/ilpi/sinais': typeof IlpiSinaisRoute
  '/publico/$slug': typeof PublicoSlugRoute
  '/selo/$areaId': typeof SeloAreaIdRoute
  '/validar/$hash': typeof ValidarHashRoute
  '/ilpi/': typeof IlpiIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/checklist/$id': typeof AuthenticatedChecklistIdRoute
  '/_authenticated/etiquetas/$unitId': typeof AuthenticatedEtiquetasUnitIdRoute
  '/_authenticated/onboarding/health': typeof AuthenticatedOnboardingHealthRoute
  '/_authenticated/onboarding/setup': typeof AuthenticatedOnboardingSetupRoute
  '/_authenticated/onboarding/step-1': typeof AuthenticatedOnboardingStep1Route
  '/_authenticated/onboarding/step-2': typeof AuthenticatedOnboardingStep2Route
  '/_authenticated/onboarding/step-3': typeof AuthenticatedOnboardingStep3Route
  '/_authenticated/painel/academias': typeof AuthenticatedPainelAcademiasRoute
  '/_authenticated/painel/acessos': typeof AuthenticatedPainelAcessosRoute
  '/_authenticated/painel/assinantes': typeof AuthenticatedPainelAssinantesRoute
  '/_authenticated/painel/assinatura': typeof AuthenticatedPainelAssinaturaRoute
  '/_authenticated/painel/capa': typeof AuthenticatedPainelCapaRoute
  '/_authenticated/painel/checklists': typeof AuthenticatedPainelChecklistsRoute
  '/_authenticated/painel/conformidade': typeof AuthenticatedPainelConformidadeRoute
  '/_authenticated/painel/documentos': typeof AuthenticatedPainelDocumentosRoute
  '/_authenticated/painel/esterilizacao': typeof AuthenticatedPainelEsterilizacaoRoute
  '/_authenticated/painel/estoque': typeof AuthenticatedPainelEstoqueRoute
  '/_authenticated/painel/insumos': typeof AuthenticatedPainelInsumosRoute
  '/_authenticated/painel/logistica': typeof AuthenticatedPainelLogisticaRoute
  '/_authenticated/painel/pastas': typeof AuthenticatedPainelPastasRoute
  '/_authenticated/painel/pmoc': typeof AuthenticatedPainelPmocRoute
  '/_authenticated/painel/precificacao': typeof AuthenticatedPainelPrecificacaoRoute
  '/_authenticated/painel/rdc': typeof AuthenticatedPainelRdcRouteWithChildren
  '/_authenticated/painel/suites': typeof AuthenticatedPainelSuitesRoute
  '/_authenticated/painel/treinamentos': typeof AuthenticatedPainelTreinamentosRoute
  '/_authenticated/superadmin/clientes': typeof AuthenticatedSuperadminClientesRoute
  '/_authenticated/superadmin/complice': typeof AuthenticatedSuperadminCompliceRoute
  '/_authenticated/superadmin/metricas': typeof AuthenticatedSuperadminMetricasRoute
  '/_authenticated/superadmin/pagamentos': typeof AuthenticatedSuperadminPagamentosRoute
  '/_authenticated/superadmin/regulatorio': typeof AuthenticatedSuperadminRegulatorioRoute
  '/q/$unitId/$token': typeof QUnitIdTokenRoute
  '/_authenticated/checklist/': typeof AuthenticatedChecklistIndexRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
  '/app/operador/': typeof AppOperadorIndexRoute
  '/_authenticated/painel/prefeituras/dashboard': typeof AuthenticatedPainelPrefeiturasDashboardRoute
  '/_authenticated/painel/rdc/diagnostico': typeof AuthenticatedPainelRdcDiagnosticoRoute
  '/_authenticated/painel/rdc/evidencias': typeof AuthenticatedPainelRdcEvidenciasRoute
  '/_authenticated/painel/rdc/plano': typeof AuthenticatedPainelRdcPlanoRoute
  '/_authenticated/painel/rdc/riscos': typeof AuthenticatedPainelRdcRiscosRoute
  '/_authenticated/painel/unidades/$id': typeof AuthenticatedPainelUnidadesIdRoute
  '/api/public/hooks/compliance-scheduler': typeof ApiPublicHooksComplianceSchedulerRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/app/operador/$unitId/$token': typeof AppOperadorUnitIdTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/_authenticated/painel/prefeituras/': typeof AuthenticatedPainelPrefeiturasIndexRoute
  '/_authenticated/painel/rdc/': typeof AuthenticatedPainelRdcIndexRoute
  '/_authenticated/painel/unidades/': typeof AuthenticatedPainelUnidadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/auth'
    | '/demo'
    | '/diagnostico'
    | '/diagnostico-escola'
    | '/diagnostico-ilpi'
    | '/entrar'
    | '/escolas'
    | '/ilpi'
    | '/intercorrencia'
    | '/lares-de-idosos'
    | '/mcp'
    | '/menu'
    | '/odontologia'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/sucesso'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/checkout'
    | '/dashboard'
    | '/gestor'
    | '/hoje'
    | '/logistica'
    | '/painel'
    | '/saude'
    | '/acao/$tipo'
    | '/auth/register'
    | '/historico/$localId'
    | '/ilpi/auditoria'
    | '/ilpi/checklists'
    | '/ilpi/sinais'
    | '/publico/$slug'
    | '/selo/$areaId'
    | '/validar/$hash'
    | '/ilpi/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/checklist/$id'
    | '/etiquetas/$unitId'
    | '/onboarding/health'
    | '/onboarding/setup'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/painel/academias'
    | '/painel/acessos'
    | '/painel/assinantes'
    | '/painel/assinatura'
    | '/painel/capa'
    | '/painel/checklists'
    | '/painel/conformidade'
    | '/painel/documentos'
    | '/painel/esterilizacao'
    | '/painel/estoque'
    | '/painel/insumos'
    | '/painel/logistica'
    | '/painel/pastas'
    | '/painel/pmoc'
    | '/painel/precificacao'
    | '/painel/rdc'
    | '/painel/suites'
    | '/painel/treinamentos'
    | '/superadmin/clientes'
    | '/superadmin/complice'
    | '/superadmin/metricas'
    | '/superadmin/pagamentos'
    | '/superadmin/regulatorio'
    | '/q/$unitId/$token'
    | '/checklist/'
    | '/painel/'
    | '/app/operador/'
    | '/painel/prefeituras/dashboard'
    | '/painel/rdc/diagnostico'
    | '/painel/rdc/evidencias'
    | '/painel/rdc/plano'
    | '/painel/rdc/riscos'
    | '/painel/unidades/$id'
    | '/api/public/hooks/compliance-scheduler'
    | '/api/public/webhooks/mercadopago'
    | '/app/operador/$unitId/$token'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/painel/prefeituras/'
    | '/painel/rdc/'
    | '/painel/unidades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/auth'
    | '/demo'
    | '/diagnostico'
    | '/diagnostico-escola'
    | '/diagnostico-ilpi'
    | '/entrar'
    | '/escolas'
    | '/intercorrencia'
    | '/lares-de-idosos'
    | '/mcp'
    | '/menu'
    | '/odontologia'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/sucesso'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/checkout'
    | '/dashboard'
    | '/gestor'
    | '/hoje'
    | '/logistica'
    | '/saude'
    | '/acao/$tipo'
    | '/auth/register'
    | '/historico/$localId'
    | '/ilpi/auditoria'
    | '/ilpi/checklists'
    | '/ilpi/sinais'
    | '/publico/$slug'
    | '/selo/$areaId'
    | '/validar/$hash'
    | '/ilpi'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/checklist/$id'
    | '/etiquetas/$unitId'
    | '/onboarding/health'
    | '/onboarding/setup'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/painel/academias'
    | '/painel/acessos'
    | '/painel/assinantes'
    | '/painel/assinatura'
    | '/painel/capa'
    | '/painel/checklists'
    | '/painel/conformidade'
    | '/painel/documentos'
    | '/painel/esterilizacao'
    | '/painel/estoque'
    | '/painel/insumos'
    | '/painel/logistica'
    | '/painel/pastas'
    | '/painel/pmoc'
    | '/painel/precificacao'
    | '/painel/suites'
    | '/painel/treinamentos'
    | '/superadmin/clientes'
    | '/superadmin/complice'
    | '/superadmin/metricas'
    | '/superadmin/pagamentos'
    | '/superadmin/regulatorio'
    | '/q/$unitId/$token'
    | '/checklist'
    | '/painel'
    | '/app/operador'
    | '/painel/prefeituras/dashboard'
    | '/painel/rdc/diagnostico'
    | '/painel/rdc/evidencias'
    | '/painel/rdc/plano'
    | '/painel/rdc/riscos'
    | '/painel/unidades/$id'
    | '/api/public/hooks/compliance-scheduler'
    | '/api/public/webhooks/mercadopago'
    | '/app/operador/$unitId/$token'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/painel/prefeituras'
    | '/painel/rdc'
    | '/painel/unidades'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ajuda'
    | '/auth'
    | '/demo'
    | '/diagnostico'
    | '/diagnostico-escola'
    | '/diagnostico-ilpi'
    | '/entrar'
    | '/escolas'
    | '/ilpi'
    | '/intercorrencia'
    | '/lares-de-idosos'
    | '/mcp'
    | '/menu'
    | '/odontologia'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/sucesso'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/checkout'
    | '/_authenticated/dashboard'
    | '/_authenticated/gestor'
    | '/_authenticated/hoje'
    | '/_authenticated/logistica'
    | '/_authenticated/painel'
    | '/_authenticated/saude'
    | '/acao/$tipo'
    | '/auth_/register'
    | '/historico/$localId'
    | '/ilpi/auditoria'
    | '/ilpi/checklists'
    | '/ilpi/sinais'
    | '/publico/$slug'
    | '/selo/$areaId'
    | '/validar/$hash'
    | '/ilpi/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/checklist/$id'
    | '/_authenticated/etiquetas/$unitId'
    | '/_authenticated/onboarding/health'
    | '/_authenticated/onboarding/setup'
    | '/_authenticated/onboarding/step-1'
    | '/_authenticated/onboarding/step-2'
    | '/_authenticated/onboarding/step-3'
    | '/_authenticated/painel/academias'
    | '/_authenticated/painel/acessos'
    | '/_authenticated/painel/assinantes'
    | '/_authenticated/painel/assinatura'
    | '/_authenticated/painel/capa'
    | '/_authenticated/painel/checklists'
    | '/_authenticated/painel/conformidade'
    | '/_authenticated/painel/documentos'
    | '/_authenticated/painel/esterilizacao'
    | '/_authenticated/painel/estoque'
    | '/_authenticated/painel/insumos'
    | '/_authenticated/painel/logistica'
    | '/_authenticated/painel/pastas'
    | '/_authenticated/painel/pmoc'
    | '/_authenticated/painel/precificacao'
    | '/_authenticated/painel/rdc'
    | '/_authenticated/painel/suites'
    | '/_authenticated/painel/treinamentos'
    | '/_authenticated/superadmin/clientes'
    | '/_authenticated/superadmin/complice'
    | '/_authenticated/superadmin/metricas'
    | '/_authenticated/superadmin/pagamentos'
    | '/_authenticated/superadmin/regulatorio'
    | '/q/$unitId/$token'
    | '/_authenticated/checklist/'
    | '/_authenticated/painel/'
    | '/app/operador/'
    | '/_authenticated/painel/prefeituras/dashboard'
    | '/_authenticated/painel/rdc/diagnostico'
    | '/_authenticated/painel/rdc/evidencias'
    | '/_authenticated/painel/rdc/plano'
    | '/_authenticated/painel/rdc/riscos'
    | '/_authenticated/painel/unidades/$id'
    | '/api/public/hooks/compliance-scheduler'
    | '/api/public/webhooks/mercadopago'
    | '/app/operador/$unitId/$token'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/_authenticated/painel/prefeituras/'
    | '/_authenticated/painel/rdc/'
    | '/_authenticated/painel/unidades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AjudaRoute: typeof AjudaRoute
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  DiagnosticoEscolaRoute: typeof DiagnosticoEscolaRoute
  DiagnosticoIlpiRoute: typeof DiagnosticoIlpiRoute
  EntrarRoute: typeof EntrarRoute
  EscolasRoute: typeof EscolasRoute
  IlpiRoute: typeof IlpiRouteWithChildren
  IntercorrenciaRoute: typeof IntercorrenciaRoute
  LaresDeIdososRoute: typeof LaresDeIdososRoute
  McpRoute: typeof McpRoute
  MenuRoute: typeof MenuRoute
  OdontologiaRoute: typeof OdontologiaRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SucessoRoute: typeof SucessoRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AcaoTipoRoute: typeof AcaoTipoRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  HistoricoLocalIdRoute: typeof HistoricoLocalIdRoute
  PublicoSlugRoute: typeof PublicoSlugRoute
  SeloAreaIdRoute: typeof SeloAreaIdRoute
  ValidarHashRoute: typeof ValidarHashRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  QUnitIdTokenRoute: typeof QUnitIdTokenRoute
  AppOperadorIndexRoute: typeof AppOperadorIndexRoute
  ApiPublicHooksComplianceSchedulerRoute: typeof ApiPublicHooksComplianceSchedulerRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
  AppOperadorUnitIdTokenRoute: typeof AppOperadorUnitIdTokenRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico-escola': {
      id: '/diagnostico-escola'
      path: '/diagnostico-escola'
      fullPath: '/diagnostico-escola'
      preLoaderRoute: typeof DiagnosticoEscolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico-ilpi': {
      id: '/diagnostico-ilpi'
      path: '/diagnostico-ilpi'
      fullPath: '/diagnostico-ilpi'
      preLoaderRoute: typeof DiagnosticoIlpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolas': {
      id: '/escolas'
      path: '/escolas'
      fullPath: '/escolas'
      preLoaderRoute: typeof EscolasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilpi': {
      id: '/ilpi'
      path: '/ilpi'
      fullPath: '/ilpi'
      preLoaderRoute: typeof IlpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intercorrencia': {
      id: '/intercorrencia'
      path: '/intercorrencia'
      fullPath: '/intercorrencia'
      preLoaderRoute: typeof IntercorrenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lares-de-idosos': {
      id: '/lares-de-idosos'
      path: '/lares-de-idosos'
      fullPath: '/lares-de-idosos'
      preLoaderRoute: typeof LaresDeIdososRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odontologia': {
      id: '/odontologia'
      path: '/odontologia'
      fullPath: '/odontologia'
      preLoaderRoute: typeof OdontologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sucesso': {
      id: '/sucesso'
      path: '/sucesso'
      fullPath: '/sucesso'
      preLoaderRoute: typeof SucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestor': {
      id: '/_authenticated/gestor'
      path: '/gestor'
      fullPath: '/gestor'
      preLoaderRoute: typeof AuthenticatedGestorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hoje': {
      id: '/_authenticated/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof AuthenticatedHojeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logistica': {
      id: '/_authenticated/logistica'
      path: '/logistica'
      fullPath: '/logistica'
      preLoaderRoute: typeof AuthenticatedLogisticaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saude': {
      id: '/_authenticated/saude'
      path: '/saude'
      fullPath: '/saude'
      preLoaderRoute: typeof AuthenticatedSaudeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/acao/$tipo': {
      id: '/acao/$tipo'
      path: '/acao/$tipo'
      fullPath: '/acao/$tipo'
      preLoaderRoute: typeof AcaoTipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/register': {
      id: '/auth_/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/$localId': {
      id: '/historico/$localId'
      path: '/historico/$localId'
      fullPath: '/historico/$localId'
      preLoaderRoute: typeof HistoricoLocalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilpi/': {
      id: '/ilpi/'
      path: '/'
      fullPath: '/ilpi/'
      preLoaderRoute: typeof IlpiIndexRouteImport
      parentRoute: typeof IlpiRoute
    }
    '/ilpi/auditoria': {
      id: '/ilpi/auditoria'
      path: '/auditoria'
      fullPath: '/ilpi/auditoria'
      preLoaderRoute: typeof IlpiAuditoriaRouteImport
      parentRoute: typeof IlpiRoute
    }
    '/ilpi/checklists': {
      id: '/ilpi/checklists'
      path: '/checklists'
      fullPath: '/ilpi/checklists'
      preLoaderRoute: typeof IlpiChecklistsRouteImport
      parentRoute: typeof IlpiRoute
    }
    '/ilpi/sinais': {
      id: '/ilpi/sinais'
      path: '/sinais'
      fullPath: '/ilpi/sinais'
      preLoaderRoute: typeof IlpiSinaisRouteImport
      parentRoute: typeof IlpiRoute
    }
    '/publico/$slug': {
      id: '/publico/$slug'
      path: '/publico/$slug'
      fullPath: '/publico/$slug'
      preLoaderRoute: typeof PublicoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selo/$areaId': {
      id: '/selo/$areaId'
      path: '/selo/$areaId'
      fullPath: '/selo/$areaId'
      preLoaderRoute: typeof SeloAreaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validar/$hash': {
      id: '/validar/$hash'
      path: '/validar/$hash'
      fullPath: '/validar/$hash'
      preLoaderRoute: typeof ValidarHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checklist/': {
      id: '/_authenticated/checklist/'
      path: '/checklist'
      fullPath: '/checklist/'
      preLoaderRoute: typeof AuthenticatedChecklistIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklist/$id': {
      id: '/_authenticated/checklist/$id'
      path: '/checklist/$id'
      fullPath: '/checklist/$id'
      preLoaderRoute: typeof AuthenticatedChecklistIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/etiquetas/$unitId': {
      id: '/_authenticated/etiquetas/$unitId'
      path: '/etiquetas/$unitId'
      fullPath: '/etiquetas/$unitId'
      preLoaderRoute: typeof AuthenticatedEtiquetasUnitIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/health': {
      id: '/_authenticated/onboarding/health'
      path: '/onboarding/health'
      fullPath: '/onboarding/health'
      preLoaderRoute: typeof AuthenticatedOnboardingHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/setup': {
      id: '/_authenticated/onboarding/setup'
      path: '/onboarding/setup'
      fullPath: '/onboarding/setup'
      preLoaderRoute: typeof AuthenticatedOnboardingSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/step-1': {
      id: '/_authenticated/onboarding/step-1'
      path: '/onboarding/step-1'
      fullPath: '/onboarding/step-1'
      preLoaderRoute: typeof AuthenticatedOnboardingStep1RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/step-2': {
      id: '/_authenticated/onboarding/step-2'
      path: '/onboarding/step-2'
      fullPath: '/onboarding/step-2'
      preLoaderRoute: typeof AuthenticatedOnboardingStep2RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/step-3': {
      id: '/_authenticated/onboarding/step-3'
      path: '/onboarding/step-3'
      fullPath: '/onboarding/step-3'
      preLoaderRoute: typeof AuthenticatedOnboardingStep3RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/academias': {
      id: '/_authenticated/painel/academias'
      path: '/academias'
      fullPath: '/painel/academias'
      preLoaderRoute: typeof AuthenticatedPainelAcademiasRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/acessos': {
      id: '/_authenticated/painel/acessos'
      path: '/acessos'
      fullPath: '/painel/acessos'
      preLoaderRoute: typeof AuthenticatedPainelAcessosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/assinantes': {
      id: '/_authenticated/painel/assinantes'
      path: '/assinantes'
      fullPath: '/painel/assinantes'
      preLoaderRoute: typeof AuthenticatedPainelAssinantesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/assinatura': {
      id: '/_authenticated/painel/assinatura'
      path: '/assinatura'
      fullPath: '/painel/assinatura'
      preLoaderRoute: typeof AuthenticatedPainelAssinaturaRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/capa': {
      id: '/_authenticated/painel/capa'
      path: '/capa'
      fullPath: '/painel/capa'
      preLoaderRoute: typeof AuthenticatedPainelCapaRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/checklists': {
      id: '/_authenticated/painel/checklists'
      path: '/checklists'
      fullPath: '/painel/checklists'
      preLoaderRoute: typeof AuthenticatedPainelChecklistsRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/conformidade': {
      id: '/_authenticated/painel/conformidade'
      path: '/conformidade'
      fullPath: '/painel/conformidade'
      preLoaderRoute: typeof AuthenticatedPainelConformidadeRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/documentos': {
      id: '/_authenticated/painel/documentos'
      path: '/documentos'
      fullPath: '/painel/documentos'
      preLoaderRoute: typeof AuthenticatedPainelDocumentosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/esterilizacao': {
      id: '/_authenticated/painel/esterilizacao'
      path: '/esterilizacao'
      fullPath: '/painel/esterilizacao'
      preLoaderRoute: typeof AuthenticatedPainelEsterilizacaoRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/estoque': {
      id: '/_authenticated/painel/estoque'
      path: '/estoque'
      fullPath: '/painel/estoque'
      preLoaderRoute: typeof AuthenticatedPainelEstoqueRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/insumos': {
      id: '/_authenticated/painel/insumos'
      path: '/insumos'
      fullPath: '/painel/insumos'
      preLoaderRoute: typeof AuthenticatedPainelInsumosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/logistica': {
      id: '/_authenticated/painel/logistica'
      path: '/logistica'
      fullPath: '/painel/logistica'
      preLoaderRoute: typeof AuthenticatedPainelLogisticaRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/pastas': {
      id: '/_authenticated/painel/pastas'
      path: '/pastas'
      fullPath: '/painel/pastas'
      preLoaderRoute: typeof AuthenticatedPainelPastasRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/pmoc': {
      id: '/_authenticated/painel/pmoc'
      path: '/pmoc'
      fullPath: '/painel/pmoc'
      preLoaderRoute: typeof AuthenticatedPainelPmocRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/precificacao': {
      id: '/_authenticated/painel/precificacao'
      path: '/precificacao'
      fullPath: '/painel/precificacao'
      preLoaderRoute: typeof AuthenticatedPainelPrecificacaoRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/rdc': {
      id: '/_authenticated/painel/rdc'
      path: '/rdc'
      fullPath: '/painel/rdc'
      preLoaderRoute: typeof AuthenticatedPainelRdcRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/suites': {
      id: '/_authenticated/painel/suites'
      path: '/suites'
      fullPath: '/painel/suites'
      preLoaderRoute: typeof AuthenticatedPainelSuitesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/treinamentos': {
      id: '/_authenticated/painel/treinamentos'
      path: '/treinamentos'
      fullPath: '/painel/treinamentos'
      preLoaderRoute: typeof AuthenticatedPainelTreinamentosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/superadmin/clientes': {
      id: '/_authenticated/superadmin/clientes'
      path: '/superadmin/clientes'
      fullPath: '/superadmin/clientes'
      preLoaderRoute: typeof AuthenticatedSuperadminClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin/complice': {
      id: '/_authenticated/superadmin/complice'
      path: '/superadmin/complice'
      fullPath: '/superadmin/complice'
      preLoaderRoute: typeof AuthenticatedSuperadminCompliceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin/metricas': {
      id: '/_authenticated/superadmin/metricas'
      path: '/superadmin/metricas'
      fullPath: '/superadmin/metricas'
      preLoaderRoute: typeof AuthenticatedSuperadminMetricasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin/pagamentos': {
      id: '/_authenticated/superadmin/pagamentos'
      path: '/superadmin/pagamentos'
      fullPath: '/superadmin/pagamentos'
      preLoaderRoute: typeof AuthenticatedSuperadminPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin/regulatorio': {
      id: '/_authenticated/superadmin/regulatorio'
      path: '/superadmin/regulatorio'
      fullPath: '/superadmin/regulatorio'
      preLoaderRoute: typeof AuthenticatedSuperadminRegulatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/app/operador/': {
      id: '/app/operador/'
      path: '/app/operador'
      fullPath: '/app/operador/'
      preLoaderRoute: typeof AppOperadorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$unitId/$token': {
      id: '/q/$unitId/$token'
      path: '/q/$unitId/$token'
      fullPath: '/q/$unitId/$token'
      preLoaderRoute: typeof QUnitIdTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel/prefeituras/': {
      id: '/_authenticated/painel/prefeituras/'
      path: '/prefeituras'
      fullPath: '/painel/prefeituras/'
      preLoaderRoute: typeof AuthenticatedPainelPrefeiturasIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/prefeituras/dashboard': {
      id: '/_authenticated/painel/prefeituras/dashboard'
      path: '/prefeituras/dashboard'
      fullPath: '/painel/prefeituras/dashboard'
      preLoaderRoute: typeof AuthenticatedPainelPrefeiturasDashboardRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/rdc/': {
      id: '/_authenticated/painel/rdc/'
      path: '/'
      fullPath: '/painel/rdc/'
      preLoaderRoute: typeof AuthenticatedPainelRdcIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRdcRoute
    }
    '/_authenticated/painel/rdc/diagnostico': {
      id: '/_authenticated/painel/rdc/diagnostico'
      path: '/diagnostico'
      fullPath: '/painel/rdc/diagnostico'
      preLoaderRoute: typeof AuthenticatedPainelRdcDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedPainelRdcRoute
    }
    '/_authenticated/painel/rdc/evidencias': {
      id: '/_authenticated/painel/rdc/evidencias'
      path: '/evidencias'
      fullPath: '/painel/rdc/evidencias'
      preLoaderRoute: typeof AuthenticatedPainelRdcEvidenciasRouteImport
      parentRoute: typeof AuthenticatedPainelRdcRoute
    }
    '/_authenticated/painel/rdc/plano': {
      id: '/_authenticated/painel/rdc/plano'
      path: '/plano'
      fullPath: '/painel/rdc/plano'
      preLoaderRoute: typeof AuthenticatedPainelRdcPlanoRouteImport
      parentRoute: typeof AuthenticatedPainelRdcRoute
    }
    '/_authenticated/painel/rdc/riscos': {
      id: '/_authenticated/painel/rdc/riscos'
      path: '/riscos'
      fullPath: '/painel/rdc/riscos'
      preLoaderRoute: typeof AuthenticatedPainelRdcRiscosRouteImport
      parentRoute: typeof AuthenticatedPainelRdcRoute
    }
    '/_authenticated/painel/unidades/': {
      id: '/_authenticated/painel/unidades/'
      path: '/unidades'
      fullPath: '/painel/unidades/'
      preLoaderRoute: typeof AuthenticatedPainelUnidadesIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/unidades/$id': {
      id: '/_authenticated/painel/unidades/$id'
      path: '/unidades/$id'
      fullPath: '/painel/unidades/$id'
      preLoaderRoute: typeof AuthenticatedPainelUnidadesIdRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/api/public/hooks/compliance-scheduler': {
      id: '/api/public/hooks/compliance-scheduler'
      path: '/api/public/hooks/compliance-scheduler'
      fullPath: '/api/public/hooks/compliance-scheduler'
      preLoaderRoute: typeof ApiPublicHooksComplianceSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/operador/$unitId/$token': {
      id: '/app/operador/$unitId/$token'
      path: '/app/operador/$unitId/$token'
      fullPath: '/app/operador/$unitId/$token'
      preLoaderRoute: typeof AppOperadorUnitIdTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPainelRdcRouteChildren {
  AuthenticatedPainelRdcDiagnosticoRoute: typeof AuthenticatedPainelRdcDiagnosticoRoute
  AuthenticatedPainelRdcEvidenciasRoute: typeof AuthenticatedPainelRdcEvidenciasRoute
  AuthenticatedPainelRdcPlanoRoute: typeof AuthenticatedPainelRdcPlanoRoute
  AuthenticatedPainelRdcRiscosRoute: typeof AuthenticatedPainelRdcRiscosRoute
  AuthenticatedPainelRdcIndexRoute: typeof AuthenticatedPainelRdcIndexRoute
}

const AuthenticatedPainelRdcRouteChildren: AuthenticatedPainelRdcRouteChildren =
  {
    AuthenticatedPainelRdcDiagnosticoRoute:
      AuthenticatedPainelRdcDiagnosticoRoute,
    AuthenticatedPainelRdcEvidenciasRoute:
      AuthenticatedPainelRdcEvidenciasRoute,
    AuthenticatedPainelRdcPlanoRoute: AuthenticatedPainelRdcPlanoRoute,
    AuthenticatedPainelRdcRiscosRoute: AuthenticatedPainelRdcRiscosRoute,
    AuthenticatedPainelRdcIndexRoute: AuthenticatedPainelRdcIndexRoute,
  }

const AuthenticatedPainelRdcRouteWithChildren =
  AuthenticatedPainelRdcRoute._addFileChildren(
    AuthenticatedPainelRdcRouteChildren,
  )

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelAcademiasRoute: typeof AuthenticatedPainelAcademiasRoute
  AuthenticatedPainelAcessosRoute: typeof AuthenticatedPainelAcessosRoute
  AuthenticatedPainelAssinantesRoute: typeof AuthenticatedPainelAssinantesRoute
  AuthenticatedPainelAssinaturaRoute: typeof AuthenticatedPainelAssinaturaRoute
  AuthenticatedPainelCapaRoute: typeof AuthenticatedPainelCapaRoute
  AuthenticatedPainelChecklistsRoute: typeof AuthenticatedPainelChecklistsRoute
  AuthenticatedPainelConformidadeRoute: typeof AuthenticatedPainelConformidadeRoute
  AuthenticatedPainelDocumentosRoute: typeof AuthenticatedPainelDocumentosRoute
  AuthenticatedPainelEsterilizacaoRoute: typeof AuthenticatedPainelEsterilizacaoRoute
  AuthenticatedPainelEstoqueRoute: typeof AuthenticatedPainelEstoqueRoute
  AuthenticatedPainelInsumosRoute: typeof AuthenticatedPainelInsumosRoute
  AuthenticatedPainelLogisticaRoute: typeof AuthenticatedPainelLogisticaRoute
  AuthenticatedPainelPastasRoute: typeof AuthenticatedPainelPastasRoute
  AuthenticatedPainelPmocRoute: typeof AuthenticatedPainelPmocRoute
  AuthenticatedPainelPrecificacaoRoute: typeof AuthenticatedPainelPrecificacaoRoute
  AuthenticatedPainelRdcRoute: typeof AuthenticatedPainelRdcRouteWithChildren
  AuthenticatedPainelSuitesRoute: typeof AuthenticatedPainelSuitesRoute
  AuthenticatedPainelTreinamentosRoute: typeof AuthenticatedPainelTreinamentosRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
  AuthenticatedPainelPrefeiturasDashboardRoute: typeof AuthenticatedPainelPrefeiturasDashboardRoute
  AuthenticatedPainelUnidadesIdRoute: typeof AuthenticatedPainelUnidadesIdRoute
  AuthenticatedPainelPrefeiturasIndexRoute: typeof AuthenticatedPainelPrefeiturasIndexRoute
  AuthenticatedPainelUnidadesIndexRoute: typeof AuthenticatedPainelUnidadesIndexRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelAcademiasRoute: AuthenticatedPainelAcademiasRoute,
  AuthenticatedPainelAcessosRoute: AuthenticatedPainelAcessosRoute,
  AuthenticatedPainelAssinantesRoute: AuthenticatedPainelAssinantesRoute,
  AuthenticatedPainelAssinaturaRoute: AuthenticatedPainelAssinaturaRoute,
  AuthenticatedPainelCapaRoute: AuthenticatedPainelCapaRoute,
  AuthenticatedPainelChecklistsRoute: AuthenticatedPainelChecklistsRoute,
  AuthenticatedPainelConformidadeRoute: AuthenticatedPainelConformidadeRoute,
  AuthenticatedPainelDocumentosRoute: AuthenticatedPainelDocumentosRoute,
  AuthenticatedPainelEsterilizacaoRoute: AuthenticatedPainelEsterilizacaoRoute,
  AuthenticatedPainelEstoqueRoute: AuthenticatedPainelEstoqueRoute,
  AuthenticatedPainelInsumosRoute: AuthenticatedPainelInsumosRoute,
  AuthenticatedPainelLogisticaRoute: AuthenticatedPainelLogisticaRoute,
  AuthenticatedPainelPastasRoute: AuthenticatedPainelPastasRoute,
  AuthenticatedPainelPmocRoute: AuthenticatedPainelPmocRoute,
  AuthenticatedPainelPrecificacaoRoute: AuthenticatedPainelPrecificacaoRoute,
  AuthenticatedPainelRdcRoute: AuthenticatedPainelRdcRouteWithChildren,
  AuthenticatedPainelSuitesRoute: AuthenticatedPainelSuitesRoute,
  AuthenticatedPainelTreinamentosRoute: AuthenticatedPainelTreinamentosRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
  AuthenticatedPainelPrefeiturasDashboardRoute:
    AuthenticatedPainelPrefeiturasDashboardRoute,
  AuthenticatedPainelUnidadesIdRoute: AuthenticatedPainelUnidadesIdRoute,
  AuthenticatedPainelPrefeiturasIndexRoute:
    AuthenticatedPainelPrefeiturasIndexRoute,
  AuthenticatedPainelUnidadesIndexRoute: AuthenticatedPainelUnidadesIndexRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGestorRoute: typeof AuthenticatedGestorRoute
  AuthenticatedHojeRoute: typeof AuthenticatedHojeRoute
  AuthenticatedLogisticaRoute: typeof AuthenticatedLogisticaRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
  AuthenticatedSaudeRoute: typeof AuthenticatedSaudeRoute
  AuthenticatedChecklistIdRoute: typeof AuthenticatedChecklistIdRoute
  AuthenticatedEtiquetasUnitIdRoute: typeof AuthenticatedEtiquetasUnitIdRoute
  AuthenticatedOnboardingHealthRoute: typeof AuthenticatedOnboardingHealthRoute
  AuthenticatedOnboardingSetupRoute: typeof AuthenticatedOnboardingSetupRoute
  AuthenticatedOnboardingStep1Route: typeof AuthenticatedOnboardingStep1Route
  AuthenticatedOnboardingStep2Route: typeof AuthenticatedOnboardingStep2Route
  AuthenticatedOnboardingStep3Route: typeof AuthenticatedOnboardingStep3Route
  AuthenticatedSuperadminClientesRoute: typeof AuthenticatedSuperadminClientesRoute
  AuthenticatedSuperadminCompliceRoute: typeof AuthenticatedSuperadminCompliceRoute
  AuthenticatedSuperadminMetricasRoute: typeof AuthenticatedSuperadminMetricasRoute
  AuthenticatedSuperadminPagamentosRoute: typeof AuthenticatedSuperadminPagamentosRoute
  AuthenticatedSuperadminRegulatorioRoute: typeof AuthenticatedSuperadminRegulatorioRoute
  AuthenticatedChecklistIndexRoute: typeof AuthenticatedChecklistIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGestorRoute: AuthenticatedGestorRoute,
  AuthenticatedHojeRoute: AuthenticatedHojeRoute,
  AuthenticatedLogisticaRoute: AuthenticatedLogisticaRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
  AuthenticatedSaudeRoute: AuthenticatedSaudeRoute,
  AuthenticatedChecklistIdRoute: AuthenticatedChecklistIdRoute,
  AuthenticatedEtiquetasUnitIdRoute: AuthenticatedEtiquetasUnitIdRoute,
  AuthenticatedOnboardingHealthRoute: AuthenticatedOnboardingHealthRoute,
  AuthenticatedOnboardingSetupRoute: AuthenticatedOnboardingSetupRoute,
  AuthenticatedOnboardingStep1Route: AuthenticatedOnboardingStep1Route,
  AuthenticatedOnboardingStep2Route: AuthenticatedOnboardingStep2Route,
  AuthenticatedOnboardingStep3Route: AuthenticatedOnboardingStep3Route,
  AuthenticatedSuperadminClientesRoute: AuthenticatedSuperadminClientesRoute,
  AuthenticatedSuperadminCompliceRoute: AuthenticatedSuperadminCompliceRoute,
  AuthenticatedSuperadminMetricasRoute: AuthenticatedSuperadminMetricasRoute,
  AuthenticatedSuperadminPagamentosRoute:
    AuthenticatedSuperadminPagamentosRoute,
  AuthenticatedSuperadminRegulatorioRoute:
    AuthenticatedSuperadminRegulatorioRoute,
  AuthenticatedChecklistIndexRoute: AuthenticatedChecklistIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface IlpiRouteChildren {
  IlpiAuditoriaRoute: typeof IlpiAuditoriaRoute
  IlpiChecklistsRoute: typeof IlpiChecklistsRoute
  IlpiSinaisRoute: typeof IlpiSinaisRoute
  IlpiIndexRoute: typeof IlpiIndexRoute
}

const IlpiRouteChildren: IlpiRouteChildren = {
  IlpiAuditoriaRoute: IlpiAuditoriaRoute,
  IlpiChecklistsRoute: IlpiChecklistsRoute,
  IlpiSinaisRoute: IlpiSinaisRoute,
  IlpiIndexRoute: IlpiIndexRoute,
}

const IlpiRouteWithChildren = IlpiRoute._addFileChildren(IlpiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AjudaRoute: AjudaRoute,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  DiagnosticoEscolaRoute: DiagnosticoEscolaRoute,
  DiagnosticoIlpiRoute: DiagnosticoIlpiRoute,
  EntrarRoute: EntrarRoute,
  EscolasRoute: EscolasRoute,
  IlpiRoute: IlpiRouteWithChildren,
  IntercorrenciaRoute: IntercorrenciaRoute,
  LaresDeIdososRoute: LaresDeIdososRoute,
  McpRoute: McpRoute,
  MenuRoute: MenuRoute,
  OdontologiaRoute: OdontologiaRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SucessoRoute: SucessoRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AcaoTipoRoute: AcaoTipoRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  HistoricoLocalIdRoute: HistoricoLocalIdRoute,
  PublicoSlugRoute: PublicoSlugRoute,
  SeloAreaIdRoute: SeloAreaIdRoute,
  ValidarHashRoute: ValidarHashRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  QUnitIdTokenRoute: QUnitIdTokenRoute,
  AppOperadorIndexRoute: AppOperadorIndexRoute,
  ApiPublicHooksComplianceSchedulerRoute:
    ApiPublicHooksComplianceSchedulerRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
  AppOperadorUnitIdTokenRoute: AppOperadorUnitIdTokenRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
